BookStore/Areas/Admin/Controllers/PublisherController.cs
using BookStore.Areas.Admin.ViewModel;
using Business.Concrete;
using DataAccess.Concrete;
using DataAccess.Concrete.EntityFramework;
using Entities.Concrete;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Areas.Admin.Controllers
{
    [RouteArea("Admin")]
    [Authorize]
    public class PublisherController : Controller
    {

        // GET: Admin/Publisher
        PublisherManager manager = new PublisherManager(new EfPublisherDal());
        MessageViewModel messageViewModel = new MessageViewModel();
        CountryManager countryManager = new CountryManager(new EfCountryDal());
        CityManager cityManager = new CityManager(new EfCityDal());


        [Route("Yayinevi")]
        [Route("Yayinevi/Index")]
        public ActionResult Index(int? SayfaNo)
        {
            //Satış Temsilcisi değilse girsin
            if (User.IsInRole("Satış Temsilcisi"))
            {
                messageViewModel.Status = false;
                messageViewModel.Message = "Yetkisiz işlem...";
                TempData["message"] = messageViewModel;
                return RedirectToAction("Index", "Login");
            }


            if (User.IsInRole("Satış Temsilcisi"))
            {
                messageViewModel.Status = false;
                messageViewModel.Message = "Yetkisiz işlem...";
                TempData["message"] = messageViewModel;
                return RedirectToAction("Index", "login");
            }


            int _sayfaNo = SayfaNo ?? 1;


            var context = new BookStoreContext();

            var List = context.Database.SqlQuery<PublisherViewModel>(@"SELECT Publishers.*, 
                                                                       Countries.CountryName, 
                                                                       Cities.CityName FROM Publishers 
                                                                       LEFT OUTER JOIN Countries ON Publishers.PublisherCountryID = Countries.ID 
                                                                       LEFT OUTER JOIN Cities ON Publishers.PublisherCityID = Cities.ID");


            var model = new List<Publisher>();

            foreach (var item in List)
            {
                model.Add(new Publisher
                {
                    ID = item.ID,
                    PublisherName = item.PublisherName,
                    PublisherDescription = item.PublisherDescription,
                    PublisherEmail = item.PublisherEmail,
                    PublisherImage = item.PublisherImage,
                    PublisherAddress = item.PublisherAddress,
                    CountryName = item.CountryName,
                    CityName = item.CityName,

                });
            }

            //var query = (from p in manager.GetAll()
            //             join c in countryManager.GetAll() on p.ID equals c.ID
            //             join ci in cityManager.GetAll() on p.ID equals ci.ID
            //             select new Publisher
            //             {
            //                 PublisherName = p.PublisherName,
            //                 PublisherDescription = p.PublisherDescription,
            //                 PublisherEmail = p.PublisherEmail,
            //                 PublisherImage = p.PublisherImage,
            //                 PublisherAddress = p.PublisherAddress,
            //                 PublisherCountry = p.PublisherCountry,
            //                 PublisherCity = p.PublisherCity,
            //                 PublisherCountryCity = c.CountryName + " / " + ci.CityName,

            //             }).OrderByDescending(x => x.ID).ToPagedList(_sayfaNo, 5);

            //var result = manager.GetAll().OrderByDescending(x => x.ID).ToPagedList<Publisher>(_sayfaNo, 5);

            return View(model.ToPagedList(_sayfaNo, 5));
        }

        public List<Country> GetCountries()
        {
            // Country-City
            CountryManager countryManager = new CountryManager(new EfCountryDal());
            List<Country> result = countryManager.GetAll();
            return result;
        }

        public ActionResult GetCity(int id)
        {
            CityManager cityManager = new CityManager(new EfCityDal());
            var result = cityManager.GetAll().Where(x => x.CountryID == id).OrderBy(x => x.CityName).ToList();
            if (result.Count == 0) { ViewBag.CityList = null; }
            else { ViewBag.CityList = new SelectList(result, "ID", "CityName"); }
            return PartialView("DisplayCity");
        }

        [Route("Yayinevi/YeniYayinevi")]
        [HttpGet]
        public ActionResult New()
        {
            //Satış Temsilcisi değilse girsin
            if (User.IsInRole("Satış Temsilcisi"))
            {
                messageViewModel.Status = false;
                messageViewModel.Message = "Yetkisiz işlem...";
                TempData["message"] = messageViewModel;
                return RedirectToAction("Index", "Login");
            }

            ViewBag.Country = new SelectList(GetCountries(), "ID", "CountryName");
            return View("PublisherForm", new Publisher());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Publisher publisher)
        {
            if (!ModelState.IsValid)
            {
                return View("PublisherForm");
            }


            if (publisher.ID == 0)
            {
                var name = manager.GetAll();
                foreach (var item in name)
                {
                    if (publisher.PublisherName == item.PublisherName)
                    {
                        messageViewModel.Status = false;
                        messageViewModel.LinkText = "YayınEvi Listesi";
                        messageViewModel.Url = "/Admin/Yayinevi";
                        messageViewModel.Message = "Bu yayınevi zaten mevcut...";
                        TempData["message"] = messageViewModel;


                        ViewBag.Country = new SelectList(GetCountries(), "ID", "CountryName");
                        GetCity(publisher.PublisherCountryID);
                        return View("PublisherForm");
                    }

                }
                if (Path.GetFileName(Request.Files[0].FileName).Length > 0)
                {
                    var extension = Path.GetExtension(Request.Files[0].FileName);
                    var newFileName = publisher.PublisherName + "-" + DateTime.Now.ToString("dd-MM-yyyy-H-mm") + extension;
                    var path = "~/Areas/Admin/Images/Publisher/" + newFileName;
                    Request.Files[0].SaveAs(Server.MapPath(path));
                    publisher.PublisherImage = "/Areas/Admin/Images/Publisher/" + newFileName;

                    manager.Add(publisher);
                    messageViewModel.Message = publisher.PublisherName + " yayinevi başarıyle eklendi...";
                }
                else
                {
                    messageViewModel.Status = false;
                    messageViewModel.Message = "Yazar resmi boş geçilemez!";
                    TempData["message"] = messageViewModel;
                    ViewBag.Country = new SelectList(GetCountries(), "ID", "CountryName");
                    GetCity(publisher.PublisherCountryID);
                    return View("PublisherForm", new Publisher());
                }
            }
            else
            {
                var updatePublisher = manager.GetById(publisher.ID);
                if (updatePublisher == null)
                {
                    return HttpNotFound();
                }

                var oldName = updatePublisher.PublisherName;
                var oldDesc = updatePublisher.PublisherDescription;
                var oldEmail = updatePublisher.PublisherEmail;
                var oldCountry = updatePublisher.PublisherCountryID;
                var oldCity = updatePublisher.PublisherCityID;

                string oldImage = updatePublisher.PublisherImage;


                var extension = Path.GetExtension(Request.Files[0].FileName);
                var newFileName = publisher.PublisherName + "-" + "Update" + "-" + DateTime.Now.ToString("dd-MM-yyyy-H-mm") + extension;
                var path = "~/Areas/Admin/Images/Publisher/" + newFileName;
                if (Path.GetFileName(Request.Files[0].FileName) != "")
                {
                    if (!oldImage.Contains("https"))
                    {
                        string fullPath = Request.MapPath("~" + oldImage);
                        if (System.IO.File.Exists(fullPath))
                        {
                            System.IO.File.Delete(fullPath);
                        }
                    }
                    Request.Files[0].SaveAs(Server.MapPath(path));
                    publisher.PublisherImage = "/Areas/Admin/Images/Publisher/" + newFileName;

                }

                if (publisher.PublisherName == oldName && publisher.PublisherDescription == oldDesc && publisher.PublisherEmail == oldEmail && publisher.PublisherCountryID
                    == oldCountry && publisher.PublisherCityID
                    == oldCity && extension == "")
                {
                    messageViewModel.Status = false;
                    messageViewModel.LinkText = "YayınEvi Listesi";
                    messageViewModel.Url = "/Admin/Yayinevi";
                    messageViewModel.Message = "Herhangi bir değişiklik yapılmadı...";
                    ViewBag.Country = new SelectList(GetCountries(), "ID", "CountryName");
                    GetCity(publisher.PublisherCountryID);
                    TempData["message"] = messageViewModel;
                    return View("PublisherForm", new Publisher());

                }
                else

BookStore/Areas/Admin/Views/Publisher/Index.cshtml
@using PagedList
@using PagedList.Mvc
@using Entities.Concrete
@model IPagedList<Publisher>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var result = (BookStore.Areas.Admin.ViewModel.MessageViewModel)TempData["message"];

}

<!-- breadcrumbs -->
<div class="w3l_agileits_breadcrumbs">
    <div class="w3l_agileits_breadcrumbs_inner">
        <ul>
            <li><a href="~/Admin/Anasayfa/Index">Anasayfa</a><span>«</span></li>

            <li>YayınEvleri</li>
        </ul>
    </div>
</div>
<!-- //breadcrumbs -->

<div class="inner_content_w3_agile_info two_in">
    <h2 class="w3_inner_tittle">YayınEvleri</h2>
    <!-- tables -->

    <div class="agile-tables">
        <b style="font-size:18px">
            @if (TempData["message"] != null)
            {
                if (result.Status)
                {

                    <div class="alert alert-success">
                        <b> @result.Message </b>
                    </div>
                }
                else
                {
                    <div class="alert alert-danger">
                        <b>  @result.Message</b>
                    </div>
                }
            }
        </b>
        <div class="w3l-table-info agile_info_shadow">
            <h3 class="w3_inner_tittle two">
                <a class="btn btn-success" href="/Admin/Yayinevi/YeniYayinevi">Yeni YayınEvi Ekle</a>
            </h3>
            <table id="tblDepartmanlar">
                <thead>
                    <tr>
                        <th>Resim</th>
                        <th>YayınEvi</th>
                        <th>Açıklama</th>
                        <th>Email</th>
                        <th>Adres</th>
                        <th>Ülke / Şehir</th>
                   
                        <th>Guncelle</th>
                        <th>Sil</th>

                    </tr>
                </thead>

                <tbody>
                    @foreach (var publisher in Model)
                    {
                        <tr>
                            <td><img src="@publisher.PublisherImage" width="100" height="100"/></td>
                            <td>@publisher.PublisherName</td>
                            @if (publisher.PublisherDescription.Length >= 100)
                            {
                                <td>@publisher.PublisherDescription.Substring(0, 100)...</td>
                            }
                            else
                            {
                                <td>@publisher.PublisherDescription</td>
                            }
                            <td>@publisher.PublisherEmail</td>
                            <td>@publisher.PublisherAddress</td>
                            <td>@publisher.PublisherCountryCity</td>
                            <td><a href="/Admin/Yayinevi/Guncelle/@publisher.ID" class="btn btn-success">Guncelle</a></td>
                            <td><a class="btn btn-danger" onclick="if (confirm('YayınEvini Silmek Istiyor musunuz?')){return true;}else{evetn.stopPropagation(); event.preventDefault();};" href="/Admin/Yayinevi/Sil/@publisher.ID">Sil</a></td>
                        </tr>
                    }
                </tbody>


            </table>

            @Html.PagedListPager(Model, _sayfaNo => Url.Action("Index", "Yayinevi", new { SayfaNo = _sayfaNo }), new PagedListRenderOptions { LinkToFirstPageFormat = "<< İlk", LinkToPreviousPageFormat = "< Önceki", LinkToNextPageFormat = "Sonraki >", LinkToLastPageFormat = "Son >>" })



        </div>

    </div>
</div>

BookStore/Areas/Admin/Views/Publisher/PublisherForm.cshtml
@using Entities.Concrete
@model Publisher
@{
    ViewBag.Title = "PublisherForm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var result = (BookStore.Areas.Admin.ViewModel.MessageViewModel)TempData["message"];

}
<!-- breadcrumbs -->
<div class="w3l_agileits_breadcrumbs">
    <div class="w3l_agileits_breadcrumbs_inner">
        <ul>
            <li><a href="~/Admin/Kategori">Anasayfa</a><span>«</span></li>

            <li>YayınEvi</li>
        </ul>
    </div>
</div>
<!-- //breadcrumbs -->



<div id="mesaj"></div>
<div class="inner_content_w3_agile_info two_in">
    <h2 class="w3_inner_tittle">Ekle &amp; Duzenle</h2>
    <!-- tables -->

    <div class="agile-tables">
        <b style="font-size:18px">
            @if (TempData["message"] != null)
            {
                if (result.Status == false)
                {

                    <div class="alert alert-danger">
                        @result.Message <b style="font-size:20px"><a href="@result.Url">@result.LinkText</a></b>
                    </div>
                }

            }
        </b>
        <div class="w3l-table-info agile_info_shadow">
            @using (Html.BeginForm("Save", "Publisher", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-group">

                    @Html.LabelFor(model => model.PublisherImage)
                    <div style="display:flex" class="col-2">
                        @*<input type="file" class="form-control" style="height:auto" name="AuthorImage" />*@
                        @Html.EditorFor(x => x.PublisherImage, new { htmlAttributes = new { @class = "form-control", type = "file", style = "height:auto", accept = "image/*", title = "Resim Yukle", onchange = "prewIMG(event)" } })
                        <img src="@Model.PublisherImage" height="52" width="52" style="position: absolute; left: calc(100% - 9.8em); " id="imgPrew" alt="Resim Yukle" />
                    </div>
                    <br />

                    @Html.LabelFor(m => m.PublisherName)
                    @Html.TextBoxFor(m => m.PublisherName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PublisherName)
                    <br />

                    @Html.LabelFor(m => m.PublisherDescription)
                    @Html.TextAreaFor(m => m.PublisherDescription, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PublisherDescription)
                    <br />

                    @Html.LabelFor(m => m.PublisherEmail)
                    @Html.TextBoxFor(m => m.PublisherEmail, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PublisherEmail)
                    <br />
                    @Html.LabelFor(m => m.PublisherAddress)
                    @Html.TextBoxFor(m => m.PublisherAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.PublisherAddress)
                    <br />

                    @if (ViewBag.Country != null)
                    {
                        @Html.LabelFor(m => m.PublisherCountryID)
                        @Html.DropDownListFor(m => m.PublisherCountryID, ViewBag.Country as SelectList, "-- Ülke Seçiniz --", new { @class = "form-control select-add-placeholder", @style = "height:auto", })
                        @Html.ValidationMessageFor(x => x.PublisherCountryID)
                    }
                    else
                    {
                        @Html.LabelFor(m => m.PublisherCountryID)
                        @Html.DropDownListFor(m => m.PublisherCountryID, new SelectList(""), "-- Ülke Bulunumadı --", new { @class = "form-control select-add-placeholder", @style = "height:auto", })
                        @Html.ValidationMessageFor(x => x.PublisherCountryID)
                    }
                    <br />

                    @if (ViewBag.CityList != null)
                    {
                        @Html.LabelFor(m => m.PublisherCityID)
                        @Html.DropDownListFor(m => m.PublisherCityID, ViewBag.CityList as SelectList, "-- Şehir Seçiniz --", new { @class = "form-control select-add-placeholder", @style = "height:auto", })
                        @Html.ValidationMessageFor(x => x.PublisherCityID)
                    }
                    else
                    {
                        @Html.LabelFor(m => m.PublisherCityID)
                        @Html.DropDownListFor(m => m.PublisherCityID, new SelectList(""), "-- Şehir Seçiniz --", new { @class = "form-control select-add-placeholder", @style = "height:auto", })
                        @Html.ValidationMessageFor(x => x.PublisherCityID)
                    }

                </div>

                @Html.HiddenFor(x => x.ID)
                <button type="submit" class="btn btn-success">Kaydet</button>

            }

        </div>

    </div>
</div>

@*bu iki kod gidip layouta yazilacak*@
@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}


<script src="~/Scripts/jquery-3.7.0.min.js"></script>

<script>

    // Resim Önizleme
    var prewIMG = function (event) {
        var result = document.getElementById("imgPrew");
        result.src = URL.createObjectURL(event.target.files[0]);
    };


    // Ülke Seçildiğinde Şehirleri Getir

    $(document).ready(function () {
        $("#PublisherCountryID").change(function () {
            var countryId = $(this).val();
            $.ajax({
                url: "/Admin/Publisher/GetCity?id=" + countryId,
                type: "POST",
                contentType: "html",
                success: function (response) {
                    debugger
                    $("#PublisherCityID").empty();
                    $("#PublisherCityID").append(response);

                }
            });
        });
    });

</script>